services:
  - type: web
    name: backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
    buildFilter:
      paths:
        - Backend/**
